name: NoverPackage
main: com.bergerkiller.bukkit.noverpackage.NoverPackage
version: 1.0
author: bergerkiller
load: startup
description: Allows dynamic package versioning applies to plugins that specify this